# docker-compose build
# docker-compose up -d web

version: '3.5'

services:
  react-app:
    container_name: react-app
    hostname: reactapp
    build:
      context: ./react-app
      dockerfile: ./Dockerfile
    volumes:
      - './react-app:/react-app'
    ports:
      - "3000:3000"
    networks:
      services-network:
        aliases:
          - react-app

  nginx:
    container_name: nginx
    image: nginx
    hostname: nginx
    volumes:
      - ./nginx/sites-enabled:/etc/nginx/conf.d:ro
      - ./logs:/var/log/nginx
      - ./nginx/certs:/etc/nginx/certs
    links:
      - react-app:react-network
    ports:
      - "8000:8000"
      - "8443:443"
    restart: on-failure:5
    networks:
      services-network:
        aliases:
           - nginx-network

networks:
  services-network:
    name: services-network
    driver: bridge
